name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - deploy/**

jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/etherface-ui
      context: .
      dockerfile: ./Dockerfile
      platforms: linux/amd64
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-prod:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/etherface-ui
      tag: sha-${{ github.sha }}
      cluster: prod
      namespace: network
      releaseName: etherface-ui
      revision: main
      dir: deploy/prod
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
